# -*- coding: utf-8 -*-
"""Parkinson's Prediction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B1cGHSULnRXxE2x0C55dyAQuBNHrlUMJ
"""

import numpy as np
import pandas as pd
import pickle

df=pd.read_csv("/content/Parkinsons.csv")
df

df.drop(['name'] ,axis=1 ,inplace=True)

df.isnull().any()

df.describe()

corr_mat=df.corr()
corr_mat["status"].sort_values(ascending=True)

y = df[["status"]]
y

x = df.drop(["status"] ,axis=1)
x

y["status"].value_counts()

print(x.shape,y.shape)

from imblearn.over_sampling import RandomOverSampler as ros
os= ros(ratio = 1)

x_df ,y_df = os.fit_sample(x,y)
print(x_df.shape , y_df.shape)

from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test = train_test_split(x_df, y_df ,test_size=0.4)

from xgboost import XGBClassifier

alg = XGBClassifier(learning_rate=0.01, n_estimators=1000, max_depth=5)
alg.fit(x_train, y_train)
predictions = alg.predict(x_test)

#pickle.dump(alg, open('parkinsons.pkl', 'wb'))

#model = pickle.load(open('parkinsons.pkl', 'rb'))
pickle.dump(alg, open('parkinsons.pickle.dat', 'wb'))

